from django.db import models

# Create your models here.
class Transaction(models.Model):
    """
    Stores the details of each M-Pesa transaction.

    This model tracks the lifecycle of an STK Push request, from initiation to the final callback result.
    It is essential for reconciling payments and providing status updates to the user.
    """
    # Unique ID generated by Safaricom for every request. Used to match callbacks to requests.
    checkout_request_id = models.CharField(max_length=100, unique=True)
    
    # ID provided by the merchant (optional, but good for internal tracking)
    merchant_request_id = models.CharField(max_length=100, blank=True, null=True)
    
    # The phone number that initiated the transaction
    phone_number = models.CharField(max_length=15)
    
    # The amount to be paid
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    
    # The receipt number generated by M-Pesa upon successful payment (e.g., QKH1234567)
    mpesa_receipt_number = models.CharField(max_length=20, blank=True, null=True)
    
    # Result code from the callback (0 means success, others indicate failure/cancellation)
    result_code = models.IntegerField(blank=True, null=True)
    
    # Descriptive message from the callback (e.g., "The service request is processed successfully.")
    result_desc = models.TextField(blank=True, null=True)
    
    # Timestamp of when the transaction was initiated
    transaction_date = models.DateTimeField(auto_now_add=True)
    
    # Current status of the transaction: Pending, Success, or Failed
    status = models.CharField(max_length=20, default="Pending")

    def __str__(self):
        return f"{self.phone_number} - {self.amount} - {self.status}"